//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuitcaseRegisttry.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaggageRegistration
    {
        public int IDBagReg { get; set; }
        public Nullable<int> IDSuitcase { get; set; }
        public Nullable<int> IDFlight { get; set; }
        public Nullable<int> Passegir { get; set; }
        public Nullable<int> WeightReg { get; set; }
        public Nullable<System.DateTime> DateReg { get; set; }
        public Nullable<int> ReceptionDesk { get; set; }
        public Nullable<int> Operator { get; set; }
        public string Cheque { get; set; }
    
        public virtual Flight Flight { get; set; }
        public virtual Suitcase Suitcase { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
