//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuitcaseRegisttry.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlackList
    {
        public int IDBlackList { get; set; }
        public Nullable<int> IDSuitcase { get; set; }
        public Nullable<int> Owner { get; set; }
        public string Reason { get; set; }
        public Nullable<int> IDLevel { get; set; }
        public Nullable<System.DateTime> DateADD { get; set; }
        public Nullable<int> AddPerson { get; set; }
        public Nullable<System.DateTime> ValidityPeriod { get; set; }
    
        public virtual Level Level { get; set; }
        public virtual Suitcase Suitcase { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
