//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuitcaseRegisttry.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfiscatedItem
    {
        public int IDConfiscatedItem { get; set; }
        public Nullable<int> IDSuitcase { get; set; }
        public Nullable<int> Inspector { get; set; }
        public string Subject { get; set; }
        public Nullable<int> IDCICategory { get; set; }
        public Nullable<int> IDDegreeProhibition { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Measurement { get; set; }
        public Nullable<System.DateTime> DateConfiscation { get; set; }
        public string Storagelocation { get; set; }
        public Nullable<int> Destroyed { get; set; }
        public Nullable<System.DateTime> DateDestroyed { get; set; }
    
        public virtual CICategory CICategory { get; set; }
        public virtual DegreeProhibition DegreeProhibition { get; set; }
        public virtual Suitcase Suitcase { get; set; }
        public virtual User User { get; set; }
    }
}
