//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuitcaseRegisttry.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Incident
    {
        public int IDIncident { get; set; }
        public Nullable<int> IDSuitcase { get; set; }
        public Nullable<int> IDFlight { get; set; }
        public Nullable<int> IDTypeIncident { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Place { get; set; }
        public string Description { get; set; }
        public Nullable<int> IDStatysTypeIncident { get; set; }
        public Nullable<int> Responsible { get; set; }
        public Nullable<int> Damage { get; set; }
    
        public virtual Flight Flight { get; set; }
        public virtual StatysTypeIncident StatysTypeIncident { get; set; }
        public virtual Suitcase Suitcase { get; set; }
        public virtual TypeIncident TypeIncident { get; set; }
        public virtual User User { get; set; }
    }
}
