//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuitcaseRegisttry.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inspection
    {
        public int IDInspection { get; set; }
        public Nullable<int> IDSuitcase { get; set; }
        public Nullable<int> Inspector { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> IDTypeInspection { get; set; }
        public Nullable<int> IDResult { get; set; }
        public string Description { get; set; }
        public string Conclusion { get; set; }
        public string PhotoEvidence { get; set; }
    
        public virtual Result Result { get; set; }
        public virtual Suitcase Suitcase { get; set; }
        public virtual TypeInspection TypeInspection { get; set; }
        public virtual User User { get; set; }
    }
}
