//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuitcaseRegisttry.AppData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SuitcaseRegistryEntities2 : DbContext
    {
        public SuitcaseRegistryEntities2()
            : base("name=SuitcaseRegistryEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BaggageRegistration> BaggageRegistration { get; set; }
        public virtual DbSet<BlackList> BlackList { get; set; }
        public virtual DbSet<CICategory> CICategory { get; set; }
        public virtual DbSet<ConfiscatedItem> ConfiscatedItem { get; set; }
        public virtual DbSet<DegreeDanger> DegreeDanger { get; set; }
        public virtual DbSet<DegreeProhibition> DegreeProhibition { get; set; }
        public virtual DbSet<Flight> Flight { get; set; }
        public virtual DbSet<Incident> Incident { get; set; }
        public virtual DbSet<Inspection> Inspection { get; set; }
        public virtual DbSet<Level> Level { get; set; }
        public virtual DbSet<Result> Result { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Statys> Statys { get; set; }
        public virtual DbSet<StatysFlight> StatysFlight { get; set; }
        public virtual DbSet<StatysTracking> StatysTracking { get; set; }
        public virtual DbSet<StatysTypeIncident> StatysTypeIncident { get; set; }
        public virtual DbSet<Suitcase> Suitcase { get; set; }
        public virtual DbSet<Tracking> Tracking { get; set; }
        public virtual DbSet<TypeIncident> TypeIncident { get; set; }
        public virtual DbSet<TypeInspection> TypeInspection { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
