//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuitcaseRegisttry.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Suitcase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Suitcase()
        {
            this.BaggageRegistration = new HashSet<BaggageRegistration>();
            this.BlackList = new HashSet<BlackList>();
            this.ConfiscatedItem = new HashSet<ConfiscatedItem>();
            this.Incident = new HashSet<Incident>();
            this.Inspection = new HashSet<Inspection>();
            this.Tracking = new HashSet<Tracking>();
        }
    
        public int IDSuitcase { get; set; }
        public string QRKod { get; set; }
        public Nullable<int> Owner { get; set; }
        public string Model { get; set; }
        public string Colour { get; set; }
        public string Matireal { get; set; }
        public Nullable<int> Weight { get; set; }
        public Nullable<int> IDDegreeDanger { get; set; }
        public string SignDanger { get; set; }
        public Nullable<int> IDStatys { get; set; }
        public Nullable<System.DateTime> DateReg { get; set; }
        public Nullable<System.DateTime> Last_Up { get; set; }
        public string Photo { get; set; }
        public string Features { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BaggageRegistration> BaggageRegistration { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BlackList> BlackList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConfiscatedItem> ConfiscatedItem { get; set; }
        public virtual DegreeDanger DegreeDanger { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Incident> Incident { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inspection> Inspection { get; set; }
        public virtual Statys Statys { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tracking> Tracking { get; set; }
    }
}
