//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuitcaseRegisttry.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tracking
    {
        public int IDTracking { get; set; }
        public Nullable<int> IDSuitcase { get; set; }
        public Nullable<int> IDFlight { get; set; }
        public string Coordinate { get; set; }
        public Nullable<int> IDStatysTracking { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public Nullable<int> Scanned { get; set; }
    
        public virtual Flight Flight { get; set; }
        public virtual StatysTracking StatysTracking { get; set; }
        public virtual Suitcase Suitcase { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
